<?php

namespace ContainerJ9GexOt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainCheckerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DomainCheckerCommand' shared autowired service.
     *
     * @return \App\Command\DomainCheckerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DomainCheckerCommand.php';

        $container->privates['App\\Command\\DomainCheckerCommand'] = $instance = new \App\Command\DomainCheckerCommand();

        $instance->setName('domain:check');
        $instance->setDescription('Check domain information');

        return $instance;
    }
}
