<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9GexOt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9GexOt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ9GexOt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ9GexOt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ9GexOt\App_KernelDevDebugContainer([
    'container.build_hash' => 'J9GexOt',
    'container.build_id' => '07c78f80',
    'container.build_time' => 1710398933,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9GexOt');
